# All gpio pin ids follow the GPIO.BCM convention
# (gpio-id instead of pin-id. eg. 17 instead of 11)

# Define your input and outputs here
gpio-setup:
  17: OUTPUT  # Thermo Relais Control

# Define your commands here
commands:
  "thermo on": set 17 HIGH
  "thermo off": set 17 LOW
